[tool.poetry]
name = "injectipy"
version = "0.1.0"
description = ""
authors = ["Wim Onderbeke <wim.onderbeke@hotmail.com>"]
readme = "README.md"
license = "MIT"
keywords = ["dependency injection"]
homepage = "https://github.com/Wimonder/injectipy"
repository = "https://github.com/Wimonder/injectipy"
documentation = "https://github.com/Wimonder/injectipy"

[tool.poetry.dependencies]
python = "^3.9"
typing-extensions = "^4.9.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
black = "^23.12.1"
mypy = "^1.8.0"
flake8 = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
