name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - Wimonder
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below to help us reproduce and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-flight checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have tested with the latest version of injectipy
          required: true
        - label: I have included a minimal reproducible example
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Actual behavior...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal Reproducible Example
      description: Please provide a minimal code example that reproduces the issue
      placeholder: |
        ```python
        from injectipy import InjectipyStore, Inject, inject

        # Your minimal example here
        ```
      render: python
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: If applicable, paste the full error message and traceback
      placeholder: |
        Traceback (most recent call last):
          ...
      render: shell

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      options:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "Other (please specify in additional context)"
    validations:
      required: true

  - type: input
    id: injectipy-version
    attributes:
      label: Injectipy Version
      description: What version of injectipy are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - "Linux"
        - "macOS"
        - "Windows"
        - "Other (please specify in additional context)"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: If you've found a workaround, please describe it
      placeholder: Describe any workaround you've found...
