name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - Wimonder
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the sections below to help us understand your request.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-flight checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have reviewed the documentation and this feature doesn't exist
          required: true
        - label: This feature would benefit the general user base, not just my specific use case
          required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        As a [type of user], I want [functionality] so that [benefit/value].

        Currently, this is not possible because...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: Describe the feature you'd like to see...
    validations:
      required: true

  - type: textarea
    id: api-example
    attributes:
      label: API Design Example
      description: If applicable, show how you imagine the API would work
      placeholder: |
        ```python
        from injectipy import InjectipyStore

        # Example of how the new feature would be used
        store = InjectipyStore()
        # ... your example here
        ```
      render: python

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: Describe alternative approaches you've considered...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that might be helpful...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would improve my workflow"
        - "High - Blocking my use case"
        - "Critical - Cannot use the library without this"
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to contribute to the implementation?
      options:
        - label: I would be willing to submit a PR for this feature
        - label: I can help with testing once implemented
        - label: I can help with documentation once implemented
